### ISSUE TITLE
RuntimeException: Canvas: trying to draw too large bitmap

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [hnvn/flutter_image_cropper#170]
java.lang.RuntimeException: Canvas: trying to draw too large(144609280bytes) bitmap.
E/AndroidRuntime(19859): 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
E/AndroidRuntime(19859): 	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:101)
E/AndroidRuntime(19859): 	at com.yalantis.ucrop.util.FastBitmapDrawable.draw(FastBitmapDrawable.java:41)
E/AndroidRuntime(19859): 	at android.widget.ImageView.onDraw(ImageView.java:1360)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21971)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20844)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20830)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21974)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20844)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20830)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20830)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)
E/AndroidRuntime(19859): 	at android.view.View.updateDisplayListIfDirty(View.java:20830)
E/AndroidRuntime(19859): 	at android.view.View.draw(View.java:21697)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.drawChild(ViewGroup.java:5150)
E/AndroidRuntime(19859): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4925)

**Comment by johnebere58** [comment]
Am having this same issue

**Comment by johnebere58** [comment]
Try adding maxWidth and maxHeight params, this should solve the issue

**Comment by 1207roy** [comment]
@johnebere58 But what should be the value of maxWidth and maxHeight?
should it be depends on device size?

**Comment by kg551915** [comment]
Same issue. The image I upload doesn't fit inside the cropper. The final cropping isn't the issue. So setting the maxWidth and maxHeight does not solve the issue since that only affects the final crop.

[Working Image](https://unsplash.com/photos/mEZ3PoFGs_k)
[Failing Image](https://unsplash.com/photos/QXevDflbl8A)

**Comment by alextrujillo4** [comment]
Getting the same issue, it seems it was the nullsafe update in v 1.4.0
