### ISSUE TITLE
Could not resolve com.github.yalantis:ucrop:2.2.10.

### ISSUE THREAD

**Issue by gereedei** [hnvn/flutter_image_cropper#542]
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.yalantis:ucrop:2.2.10.
     Required by:
         project :app > project :image_cropper
      > Could not resolve com.github.yalantis:ucrop:2.2.10.
         > Could not get resource 'https://www.jitpack.io/com/github/yalantis/ucrop/2.2.10/ucrop-2.2.10.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/yalantis/ucrop/2.2.10/ucrop-2.2.10.pom'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

how to get it working?

**Comment by kumphol** [comment]
Same here. I updated version to 8.0.2 and 8.1.0 this error still occurred.

**Comment by hunterwilhelm** [comment]
Same here, downgrading to 8.0.2
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1 24B83 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

**Comment by gereedei** [comment]
> Same here, downgrading to 8.0.1 [✓] Flutter (Channel stable, 3.27.1, on macOS 15.1 24B83 darwin-arm64, locale en-US) [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

how did you downgrade to 8.0.1?

**Comment by hunterwilhelm** [comment]
@gereedei Sadly the downgrade still didn't work.
But to answer your question: `flutter pub add image_cropper:"^8.1.0"`
Or by replacing the line in your pubspect.yaml
```
  image_cropper: ^8.1.0
```
See: https://pub.dev/packages/image_cropper/versions/8.0.1/install

**Comment by hnvn** [comment]
It's related to fetch data from library repositories which is jitpack.io in this case, I am afraid that we have no solution rather than we jitpack.io fixes that issue.

**Comment by hunterwilhelm** [comment]
@gereedei Downgrading to 7.1.0 worked!
@hnvn Good to know, thanks

**Comment by hnvn** [comment]
@hunterwilhelm I think that `7.1.0` works for you because there's a caching of ucrop library in your machine

**Comment by gereedei** [comment]
> @gereedei Downgrading to 7.1.0 worked! @hnvn Good to know, thanks

how did you downgrade? i had few dependancies error when trying to downgrade to 7. plus it works on ios, and it seems only andriod has this issue

**Comment by jaganzutual** [comment]
7.1.0 is not working for me

**Comment by Richard-Van-Intania** [comment]
same here

**Comment by quyenlv-unicloud** [comment]
jitpack for ucrop up now, issue resolved if you can access https://www.jitpack.io/com/github/yalantis/ucrop/2.2.10/ucrop-2.2.10.pom

but no idea when it down again as it downed 15+ times this year, only solution is uCrop publish to maven central

**Comment by hunterwilhelm** [comment]
> @hunterwilhelm I think that `7.1.0` works for you because there's a caching of ucrop library in your machine

@hnvn Very plausible, I was on   image_cropper: ^1.5.1 before.

**Comment by hunterwilhelm** [comment]
@jaganzutual @Richard-Van-Intania @gereedei 
`image_cropper: ^8.1.0` works now! (because jitpack is operational again)

If anyone has any issues with uCrop, try checking: https://status.jitpack.io/

**Comment by hnvn** [comment]
it will close this issue because it is resolved now

**Comment by richanshah** [comment]
i still face issue wirh latest version when i am using this library in one of my flutter module

**Comment by richanshah** [comment]
i have fixed by adding in setting.gradle         maven { url 'https://jitpack.io' } // JitPack repository
